import streamlit as st
import io
from PIL import Image, ImageDraw, ImageFont


st.set_page_config(page_title="ELAN 2022 Certification", page_icon=None,
                   layout="centered", initial_sidebar_state="collapsed", menu_items=None)


background = Image.open("./new_banner.png")
col1, col2, col3 = st.columns([0.2, 5, 0.2])
col2.image(background, use_column_width=True)

events_data = {
    "Infinity - Logo Design": [
        "Banda Shambhavi",
        "Choragudi Saikeerthi",
        "Pocha Subhashini",
        "Kamalapuram Vinay",
        "Mudavath Preethi",
        "Mudhiraj Praneetha",
        "Kumbojji Uday Kiran",
        "Kammari Uday kiran",
        "Singamsetty Navya",
        "Kukkapalli Madhuri",
        "Pasula Sandhya Rani",
        "Kowluri Ajay",
        "K Shashidhar",
        " Kondu Manisha",
        "G Tharun",
        "Bharathkavi Sirisha",
        "Paka Roshini",
        "Daddanala Sravani",
        "Mohammed Sameera",
        "B Saikumar",
        "CH Dinesh",
        "Sadaf Sultana",
        "B Saikumar",
        "Kammari Uday kiran"
    ],
    "Ad - Zap": [
        "Bhargavi ",
        "Ramya",
        "Ajay",
        "Siddhardha",
        "Pravallika",
        "Akshitha",
        "Sharath goud",
        "Abhishek ",
        "Anuth reddy",
        "ch. Ramya",
        "B.Vinny Reddy",
        "B. bhuvaneswari",
        "B.Mahima",
        "C. Nikitha",
        "M. Vaishnavi ",
        "G.kanakaraju",
        "A. Nikhilsai",
        "Akash Pandey",
        "D. Bhavana",
        "G. Akshaya",
        "D.Navya",
        "B.Kalyan",
        "C.Vijay Sagar",
        "G. Ashish",
        "Siddhardha",
        "Pravallika",
        "Akshitha",
        "Bhargavi",
        "Ramya",
        "Ajay"
    ],
    "Sherlock and Watson": [
        "D.Santhosh Kumar",
        "M.Rosy Kumari",
        "B.Manisha",
        "P.Padmavathi",
        "Potnuru Sai",
        "B.Divya",
        "Ameesha Roy",
        "B.Sirisha",
        "G.Sonali",
        "Ch.Usha Rani",
        "YS.Keerthi",
        "Varsha Vijayan",
        "N.Kranthi",
        "M.Sumanth",
        "G.Bhavya",
        "D.Pallavi",
        "B.Siddhardha",
        "V.Pravalika",
        "S.Sanjana",
        "B.Sai Kumar",
        "N.Meghana",
        "P.Sahithi",
        "B.Rishi",
        "Ch.Bhavani Chary",
        "Madiha Ammatul Rasool",
        "Jatta Nandini",
        "N.Geetha",
        "R.Nithin"
    ],
    "Crack the Code": [
        "Komirelly Uma Maheshwari",
        "Mohammad sohail",
        "Boddu Ramesh",
        "Injapuri Rama Krishna ",
        "Kairamkonda Akhila",
        "Munna Nandini",
        "K.Bharath",
        "K.Shiva kumar",
        "A.Laxmi",
        "A.Poojitha",
        "D.Nagarani",
        "M. Preethi",
        "M.Aswitha",
        "M.Nithin sai",
        "Potnuru Sai",
        "P.Sai kiran",
        "P.Khageswara rao",
        "Bhargavi",
        "Ramya",
        "Pravalika",
        "M.Uday kiran",
        "J.Nandini",
        "D.Akila",
        "Sravan kumar.l",
        "Harish.E",
        "Srikanth.U",
        "G.Shrath kumar ",
        "D.Ganesh ",
        "A.Shiva shankar ",
        "V.Divya",
        "T.Manasa",
        "A.Sravya",
        "Mailaram.Shambhavi",
        "Conelakanchu Keerthana",
        "Miza Nabeel ali baig",
        "D.sneha",
        "B.ruchika",
        "B.Srichandana",
        "R.Monoj",
        "R.Anish",
        "R.Sanketh",
        "Mounika.N",
        "Akhil raja",
        "Monisha",
        "Ashish",
        "Surya pratap",
        "B.Rohan",
        "M.Naveen kumar ",
        "M.Hari Krishna ",
        "K.Siddarth chary ",
        "Saharsha sai",
        "Karthik",
        "Azeez",
        "S.Charan",
        "P.Sai krishna ",
        "V.Bharath",
        "S.Usha Rani",
        "Tharsha vardhan reddy",
        "T.Akhil",
        "H.Gurunath",
        "J.Satish kumar ",
        "K.Charan Reddy ",
        "Panjala sandeep goud ",
        "A.Srivani",
        "Abhishek.M",
        "J.Mahesh",
        "B.Rakesh",
        "Balla sowmya ",
        "B.Vinny reddy",
        "Panuganti.Shireesha",
        "Akash Pandey",
        "D.Bhavana",
        "G.Akshaya",
        "A.Nikhil sai ",
        "Ch.Parthe reddy ",
        "D.Sai prasad ",
        "A.Aravind",
        "G.Tharun",
        "Ch.Dattaprasad ",
        "Asma ",
        "J.Nikitha ",
        "G. Vamshee",
        "E.Nivas",
        "G.Vinay ",
        "T.Ravalikha",
        "L.Nandhini",
        "Jamalpur shambhavi",
        "B.Manoj kumar",
        "Dev Pareek",
        "C.Nikitha",
        "A.Spoorthi reddy ",
        "V.Akash ",
        "C.Pavankumar",
        "P.Syam babu",
        "C.Vaishnavi",
        "B.Laxman",
        "B.Tharun Kumar ",
        "B.Bhuvaneshwari",
        "G.Bhavya",
        "Ch.Ramya",
        "M.Priyanka",
        "K.Keerthana",
        "K.Jithendhar",
        "Ch.Sachin kumar ",
        "B.Rahul",
        "K.Shirish ",
        "M.Anji",
        "Kalyan",
        "Vijay",
        "A.sai pavan",
        "P.Rakesh",
        "B.Malleshwari",
        "B.Swathi",
        "Ch.Keerthana",
        "B.Sai Vikas Goud ",
        "Ch.Sandeep kumar ",
        "Manish kumar ",
        "Shaik Nasreen ",
        "Mohan Naik ",
        "Srikanth",
        "Chethan",
        "P.Yashswini ",
        "V.Hothika roni ",
        "Chiliveri.Sahithi",
        "Pulluri.Keerthana ",
        "Madupathi.Navya",
        "Kasturi.Ronith",
        "Babur.Rohith",
        "Gondala.Ravi kiran",
        "D.Poojitha",
        "D.Navya",
        "D.Pallavi",
        "V.Praneeth reddy ",
        "S.Ajay",
        "M.Mamatha",
        "A.Manoj Kumar ",
        "B.Anvesh nayak",
        "D.Akhil",
        "Ch.Bala surabhi",
        "B.Rishi",
        "Ch.Bhavani chary ",
        "Odapalli Santosh kumar ",
        "Palcha.Bhargavi",
        "Perumula.Bharadwaja",
        "Katta deppak venkata krishna ",
        "Mohammed riyaaz",
        "Jakkani.Sai kiran",
        "Matam.Varahasri",
        "Sripriya.Kolavi",
        "Raju goud.j",
        "P.Raghu",
        "M.Sanjaykumar",
        "B.Sandeep ",
        "M.Sanjana ",
        "L.Nikhileshwar",
        "K.Venkatesh",
        "T.Jai Raghav",
        "T.Yashwanth",
        "Asif Hussian",
        "M.Navya",
        "C.Sahithi",
        "P.Keerthana"
    ],
    "Capes": [
        "Subasri B",
        "G Ruchitha",
        "G Sindhu priya",
        "M Nithin sai",
        "Sai kiran",
        "Kiran",
        "Sai kiran",
        "M Naveen Kumar",
        "M Hari krishna",
        "K Sidhartha Chary",
        "L Sravan Kumar",
        "Asma",
        "J Nikitha",
        "Archana ",
        "J Srikanth",
        "Ch Sachin Kumar",
        "B Rahul",
        "Vema Reddy",
        "Rohan",
        "Suryaprathap singh",
        "A pavan",
        "E Nivas",
        "G Vinay",
        "G Vamshee",
        "K Vinay",
        "J Nandini",
        "M Varsha ",
        "G Sharath Kumar",
        "K srivani",
        "S Maithriyi",
        "V HothnikaRani",
        "P Yashaswini",
        "M Janavi",
        "B Sai Jyoshna",
        "O Ganesh",
        "B Malleshwari",
        "K Jacintha Su Zan",
        "D Sai Prasad",
        "A Preethi",
        "Tharun",
        "Likitha",
        "Nithin Sai",
        "Sai kiran",
        "P kiran Kumar",
        "P Sai",
        "B Tharun Kumar",
        "G Ravi Kiran",
        "A Manoj Kumar",
        "B Rohit",
        "Charan Reddy",
        "M Sumanth",
        "E Harish",
        "Ch Krishna",
        "S Lavanya",
        "E pooja",
        "S urmila",
        "G Kanakaraju",
        "Tsm Naveen Kumar",
        "V Raj kumar",
        "S Saketh",
        "P Sai Akshitha",
        "B Siddhardha",
        "J Gopi",
        "M Ahwitha",
        "M Preethi",
        "M Uma Latha",
        "N Balaraju",
        "C jashwanth Reddy",
        "S ashritha Reddy",
        "M Praneetha ",
        "B shambhavi",
        "B sanghavi",
        "V Vaishnavi",
        "B sai kumar ",
        "S Sravan",
        "S Sanjana ",
        "V shiva",
        "YS Keerthi",
        "J Rishitha",
        "TP Sneha",
        "D Bhavana",
        "G Akshaya",
        "Ch Ramya",
        "G Bhavya",
        "D Navya",
        "D Pallavi",
        "B Bhuvaneshwari",
        "P Shireesha",
        "shaik maheen",
        "Bandi Vinny Reddy",
        "J Sathish Kumar",
        "J Raju Goud",
        "H Gurunath",
        "J sai kiran ",
        "A Shiva shankar",
        "M Uday kiram",
        "Ch Bhavani Chary",
        "B Rishi",
        "Ch Sai keerthi",
        "G sowjanya",
        "P Subhashini",
        "K Shalini",
        "S Niharika",
        "P Pavani",
        "N Pavani ",
        "K Karunakar Reddy",
        "S Saketh",
        "V Rajkumar",
        "T Akhil",
        "Harsha",
        "R Veena",
        "R Nithin",
        "N Geetha",
        "Palak"
    ],
    "Stand Up Comedy": [
        "A. Nikhil sai",
        "V. Suresh Nayak",
        "Bandi Vinny Reddy",
        "B. Bhuvaneshwari",
        "M.Rama Krishna",
        "Tara",
        "N. Geetha",
        "G. Sharath Kumar"
    ],
    "Young Manager": [
        "D.Santosh RaviTteja",
        "S.Navya",
        "Akanksha Dubey",
        "B.Sanghavi",
        "Dev Pareek",
        "J.Shambhavi",
        "A.Preethi"
    ],
    "Scratch your Talent": [
        "K.Karthik",
        "M.D.Mateen",
        "P.Kiran kumar",
        "CH.Datta Prasad",
        "N.Anaina",
        "J.Nandini",
        "k.Srihitha",
        "G.Kanaka Raju",
        "S.Anusha",
        "Sharath Goud",
        "T.P.Sneha",
        "N.Geetha",
        "R.Nithin",
        "B.Sanghavi",
        "B.Shambhavi",
        "P.Sai Akshitha",
        "V.Vaishnavi"
    ],
    "Tata Birla Startup Talk": [
        "Alan ",
        "Jasnavi",
        "Sadf Sultana",
        "Akanksha Dubey",
        "Navya",
        "Praneetha",
        "Manish",
        "D.Hanuman",
        "Gnanedra"
    ]
}


PATH = "./elan_cert.png"

font = ImageFont.truetype("Poppins-Medium.ttf", 80)
event_font = ImageFont.truetype("Poppins-Medium.ttf", 60)
events = st.selectbox("Select Event name", events_data.keys())
name = st.selectbox(
    "Select your name for generating certificate", events_data[events])
name = name.title()
im = Image.open(PATH)
d = ImageDraw.Draw(im)

W, H = im.size
w, h = d.textsize(name, font=font)
e_w, e_h = d.textsize(events, font=event_font)
print(w, h)
d.text(((((W-w)/2) + 105, ((H - h)/2) + 300)),
       name, fill=(56, 56, 56), font=font)
d.text(((((W-e_w)/2) - 1050, ((H - e_h)/2) + 540)),
       events, fill=(56, 56, 56), font=event_font)
if st.button("Get Certificate"):
    ioData = io.BytesIO()
    im.save(ioData, format='PNG', quality='keep')
    finalImage = ioData.getvalue()
    st.image(finalImage)

hide_streamlit_style = """
            <style>
            #MainMenu {visibility: hidden;}
            footer {visibility: hidden;}
            </style>
            """
st.markdown(hide_streamlit_style, unsafe_allow_html=True)
